### ISSUE TITLE
[TASK]공유하기 기능 구현

### ISSUE THREAD

**Issue by jiyuunyang** [codestates/MuscleFormula#126]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 공유하기 기능 구현

### TODO
1. [x] 서버로 운동기록 보내기
2. [x] 공유하기 클릭시 서버로 기록 가져오기 연결 
3. [x] 에디터에 공유한 기록 구현하기

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Urgency: `Middle`
