### ISSUE TITLE
[Task] 더미데이터 생성

### ISSUE THREAD

**Issue by kim-kyoungyeon** [codestates/MuscleFormula#226]
### ISSUE
- Group:  `client`  
- Type:   `feature` 
- Detail: 포스트 게시물 더미데이터 생성

### TODO
1. [ ] 썸네일 이미지 더미 데이터 
2. [ ] 제목 더미 데이터 
3. [ ] 포스트 내용 더미 데이터
4. [ ] 운동 부분 더미데이터
5. [ ] 난이도 더미데이터
6. [ ] 좋아요, 댓글 더미데이터
7. [ ] 닉네임 더미데이터

### Estimated time
> Pick one
 
### Labels
- Estimated time: `E: 3h`
- Group : `client` 
 
- Urgency: `High`
