### ISSUE TITLE
[Task] 공통 css 작업

### ISSUE THREAD

**Issue by kim-kyoungyeon** [codestates/MuscleFormula#234]
### ISSUE
- Group:   `sr`
- Type:   `feature` 
- Detail:  front 공통css작업

### TODO
1. [x] auth 관련 페이지 css 
2. [x] mypage  button Tag 관련   css 작업
3. [x] main page , edit page, detail page post 관련 css 작업

### Estimated time
> Pick one
 
### Labels
- Estimated time: `E: 3h`
- Group : `client` 
 
- Urgency: `High`
