### ISSUE TITLE
[Task] 랜딩페이지 랜더링 

### ISSUE THREAD

**Issue by kim-kyoungyeon** [codestates/MuscleFormula#236]
### ISSUE
- Group:  `client` 
- Type:  `feature` 
- Detail: 랜딩페이지 틀 작업
### TODO
1. [x]  스크롤 다운 이벤트에 따른 css처리(애니메이션)
2. [x] 화면에 나타낼 설명 및 기능 정리
3. [x] 화면에 보여줄 이미지 선정

### Estimated time
> Pick one
 
### Labels
- Estimated time: `E: 24h`
- Group : `client` 
 
- Urgency: `High`
