### ISSUE TITLE
[Task]메인페이지 운동시간에따른  순위,   마이페이지 어제, 오늘,개인운동 최고기록 응답 구현

### ISSUE THREAD

**Issue by KAPUIST** [codestates/MuscleFormula#242]
### ISSUE
- Group:  `server`
- Type:  `feature`
- Detail: 메인페이지 운동기록 순위, 마이페이지 개인 운동기록 응답 구현

### TODO
1. [x] 메인페이지 순위 응답
2. [x] 개인운동기록 어제, 오늘, 최고기록 응답
3. [x] 변수명 수정, 사용하지않는 엔티티 컬럼 삭제,
4. [x] 버그수정

### Estimated time
> ### `5h`

### Labels
- Estimated time: `E: 5h`
- Group :  `server`
- Urgency: `Middle`
