### ISSUE TITLE
[TASK] 모바일 환경 CSS 구현

### ISSUE THREAD

**Issue by jiyuunyang** [codestates/MuscleFormula#25]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 모바일 환경에서 최적화된 CSS 구현

### TODO
1. [x] Navigator가 모바일 크기일 때 변경되도록 만들기
2. [x] 메뉴 및 알림창 드롭 다운 구현하기
3. [ ] 컴포넌트 슬라이딩 (왼쪽, 오른쪽 슬라이딩) 구현하기

### Labels
- Estimated time: `E: 4h`
- Group : `client`
- Urgency: `Middle`
