### ISSUE TITLE
[TASK] CSS 보완

### ISSUE THREAD

**Issue by jiyuunyang** [codestates/MuscleFormula#282]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: CSS 전반 관리

### TODO
1. [x] Landing페이지 CSS 수정
2. [x] 난이도 숫자를 별로 바꾸는 컴포넌트/함수 작성
3. [x] Detail 페이지와 Editor페이지 CSS 맞추기

### Labels
- Estimated time: `E: 5h`
- Group : `client`
- Urgency: `Middle`
