### ISSUE TITLE
[TASK] 배포 후 생기는 오류 해결

### ISSUE THREAD

**Issue by ChooHongWook** [codestates/MuscleFormula#338]
### ISSUE
- Group:  `client`, `server`
- Type: `bug`
- Detail: fix actions from client redux

### TODO
1. [x] 기능들 전부 정상작동 확인
2. [x] Server 시간대 오류 확인
3. [x] 마지막 디자인 점검

### Labels
- Estimated time: `E: 2h`
- Group : `client`, `server`
- Urgency:  `Middle`
