### ISSUE TITLE
[TASK]  컴포넌트 목업 제작

### ISSUE THREAD

**Issue by jiyuunyang** [codestates/MuscleFormula#51]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 컴포넌트 목업 제작

### TODO
1. [x] 네비게이터 컴포넌트 드롭다운 구현
2. [x] 검색 컴포넌트 목업 제작
3. [x] 오늘의 운동왕 컴포넌트 목업 제작
4. [x] 포스트 썸네일 컴포넌트 목업 제작
5. [x] 포스트 컴포넌트 목업 제작

### Labels
- Estimated time: `E: 8h`
- Group : `client`
- Urgency: `Middle`
