### ISSUE TITLE
[TASK] 캘린더 컴포넌트 제작

### ISSUE THREAD

**Issue by jiyuunyang** [codestates/MuscleFormula#74]
### ISSUE
- Group:  `client`
- Type:  `feature`
- Detail: 캘린더에 기록 남기는 컴포넌트 제작

### TODO
1. [x] 캘린더 컴포넌트 틀 만들기
2. [x] 캘린더 컴포넌트에 기록 남기기 기능 구현
3. [x] 서버로 기록 보내기 구현

### Labels
- Estimated time: `E: 5h`
- Group : `client`
- Urgency: `Middle`
