### ISSUE TITLE
[TASK] 운동기록 컴포넌트 제작

### ISSUE THREAD

**Issue by jiyuunyang** [codestates/MuscleFormula#83]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 오늘의 운동을 기록하는 컴포넌트를 제작해야함

### TODO
1. [x] 운동기록 컴포넌트 목업 구현
2. [x] 기록을 재는 타이머 기능 구현
3. [x] 서버로 데이터 보내기 구현

### Labels
- Estimated time: `E: 4h`
- Group : `client`
- Urgency: `High`
