### ISSUE TITLE
[TASK]  Server와 Client를 연결

### ISSUE THREAD

**Issue by ChooHongWook** [codestates/MuscleFormula#84]
### ISSUE
- Group:  `client`, `server`,
- Type: `feature`
- Detail: 필요한 기능에 맞는 엔드포인트 연결

### TODO
1. [ ] 로그인 페이지 연결
2. [ ] 회원가입 페이지 연결
3. [ ] 운동기록 페이지 연결
4. [ ] 메인페이지 연결
5. [ ] 마이페이지 연결

### Labels
- Estimated time: `E: 5h`
- Group : `client`, `server`
- Urgency: `Middle`
